# Generated by Django 3.2 on 2022-02-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arduino_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_temp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Weather Temperature')),
                ('w_humidity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Weather Humidity')),
                ('l_humidity_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Land Humidity 1')),
                ('l_humidity_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Land Humidity 2')),
            ],
        ),
    ]
