# Generated by Django 3.2 on 2022-02-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number:')),
                ('mail', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email:')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location:')),
                ('slogan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Slogan:')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title:')),
                ('title1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title 2:')),
                ('title2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title 3:')),
                ('text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Text:')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Us_Punk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Text:')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Title:')),
                ('title2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title 2:')),
                ('title3', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Title 3:')),
                ('context', models.TextField(blank=True, null=True, verbose_name='Content: ')),
                ('features_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Futures 1:')),
                ('features_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Futures 2:')),
                ('features_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Futures 3:')),
                ('features_4', models.CharField(blank=True, max_length=100, null=True, verbose_name='Futures 4:')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title:')),
                ('title_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title:')),
                ('title1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title:')),
                ('text1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Text:')),
                ('photo1', models.FileField(blank=True, null=True, upload_to='', verbose_name='Photo: ')),
                ('title2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title:')),
                ('text2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Text:')),
                ('photo2', models.FileField(blank=True, null=True, upload_to='', verbose_name='Photo: ')),
                ('title3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title:')),
                ('text3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Text:')),
                ('photo3', models.FileField(blank=True, null=True, upload_to='', verbose_name='Photo: ')),
                ('title4', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title:')),
                ('text4', models.CharField(blank=True, max_length=100, null=True, verbose_name='Text:')),
                ('photo4', models.FileField(blank=True, null=True, upload_to='', verbose_name='Photo: ')),
            ],
        ),
    ]
