# Generated by Django 3.2 on 2022-02-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='title2',
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='title1',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Title 2:'),
        ),
    ]
