# Generated by Django 3.2 on 2022-02-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220210_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Title:'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title2',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Title 2:'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Title 3:'),
        ),
        migrations.AlterField(
            model_name='services',
            name='text1',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Text:'),
        ),
    ]
